### ISSUE TITLE
works in dev, but not in staging and prod - dockerized and all

### ISSUE THREAD

**Issue by incognos** [maciej-gol/tenant-schemas-celery#143]
Hi, been trying to figure this out for the last week and I am still unable to understand the why. probably something to do with how this is hosted but it is dockerized and this feels like something strange.

Essentially, when I add a transaction to the database, I then run an async task to copy this transaction - denormalized - to a bi table elsewhere. Async as to not hold up the response and the work is not dependent on the request.

the task is called `record_transaction` and I call it simply with `record_transaction.delay(transaction_id)` - transaction_is is the transaction that was just committed to the db.

in dev it works like a dream, the worker picks up the task and records the transaction dutifully the path is set to the tenant_schema and public. I am running staging and prod on Digital Ocean "App Platform" - worker is using their worker service, whereas the app is a web service.

But, in staging and in prod, the path is only set to `public` and I cannot seem to understand why it is a different behavior.

## Here is some of the relevant code:

```
import os

# from celery import Celery
import scout_apm.celery
from django.conf import settings
from tenant_schemas_celery.app import CeleryApp as TenantAwareCeleryApp

# Set the default Django settings module for the 'celery' program.
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "project.settings.base")

app = TenantAwareCeleryApp()

# Using a string here means the worker doesn't have to serialize
# the configuration object to child processes.
app.config_from_object("django.conf:settings")

# Load task modules from all registered Django apps.
app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)

scout_apm.celery.install(app)
```

## The task definition:

```from bi.models import Ticket, Transaction
from celery import shared_task
from django.db import transaction

# from project.celery import app
from tenant_schemas_celery.task import TenantTask
from tickets.models import TicketSold, TicketSoldTransaction


class TicketingTenantTask(TenantTask):
    abstract = True    
    max_retries = 5

    def on_failure(self, exc, task_id, args, kwargs, einfo):
        """Error handler.

        This is run by the worker when the task fails.

        Arguments:
            exc (Exception): The exception raised by the task.
            task_id (str): Unique id of the failed task.
            args (Tuple): Original arguments for the task that failed.
            kwargs (Dict): Original keyword arguments for the task that failed.
            einfo (~billiard.einfo.ExceptionInfo): Exception information.

        Returns:
            None: The return value of this handler is ignored.
        """
        sentry_sdk.capture_exception(exc, 
                                     scope=self.request, 
                                     extra={
                                         "task_id": task_id, 
                                         "args": args, 
                                         "kwargs": kwargs, 
                                         "einfo": einfo})

# @app.task(retry_backoff=True, retry_backoff_max=600, autoretry_for=(Exception,))
@shared_task(base=TicketingTenantTask, name="record_transaction", bind=True)
def record_transaction(self, transaction_id):
    """Record a transaction in the BI database."
    """
    try:
        with transaction.atomic():
             ## bunch of code here ##
    except Exception as e:
         self.retry(exc=e)
        self.retry(exc=e)
        sentry_sdk.capture_exception(e, 
                                scope=self.request, 
                                extra={
                                    "task_id": self.task_id, 
                                    "args": self.args, 
                                    "kwargs": self.kwargs, 
                                    "einfo": self.einfo})

        return 'FAILED'
    return 'SUCCESS'
```

## packages (edited for brevity)

```celery==5.4.0
Django==4.2.20
django-celery-beat==2.7.0
django-celery-results==2.5.1
django-redis==5.4.0
django-tenants==3.7.0
django-tenant-users==2.1.0
psycopg2-binary==2.9.10
sentry-sdk==2.23.1
tenant-schemas-celery==3.0.0
```

## docker file:

```
FROM python:3.10-buster as base
ENV PYTHONUNBUFFERED=1
EXPOSE 80
USER root
RUN addgroup ticketing
RUN adduser --disabled-password --gecos '' --ingroup ticketing --home /home/ticketing ticketing
RUN mkdir /home/ticketing/app
RUN chown -R ticketing:ticketing /home/ticketing
# Install uWSGI
RUN pip install uwsgi
# Copy the base uWSGI ini file to enable default dynamic uwsgi process number
COPY /docker/uwsgi.ini /etc/uwsgi/
# Which uWSGI .ini file should be used, to make it customizable
ENV UWSGI_INI /etc/uwsgi/uwsgi.ini
WORKDIR /home/ticketing/app

USER ticketing:ticketing

COPY --chown=ticketing:ticketing . /home/ticketing/app/

RUN pip install -r requirements.txt && \
    bash -c "DEBUG=True RUN_ENV=staging SECRET_KEY=placeholder12345678 ALLOWED_HOSTS=localhost,nohost DATABASE_NAME=ticketing DATABASE_USER=ticketing DATABASE_PASS=nopass python ticketing/manage.py collectstatic --no-input"
FROM base as api

CMD uwsgi

FROM base as migrator

CMD python ticketing/manage.py migrate --noinput

FROM base as worker

WORKDIR /home/ticketing/app/ticketing

CMD python -m celery -A project worker --loglevel=INFO

FROM base as beat

WORKDIR /home/ticketing/app/ticketing

CMD python -m celery -A project beat --loglevel=INFO -S tenant_schemas_celery.scheduler.TenantAwareScheduler

FROM base as flower

WORKDIR /home/ticketing/app/ticketing

CMD python -m celery -A project flower
```

## Docker compose (only used for local dev)

```
volumes:
  db-data: {}

networks:
  ticketing_public:
    name: ticketing_public

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=ticketing
      - POSTGRES_USER=ticketing
      - POSTGRES_PASSWORD=ticketing
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:6
    environment:
      - REDIS_DEFAULT_USER=guest
      - REDIS_DEFAULT_PASS=guest
  api:
    build:
      context: .
      target: api
    env_file: .env
    volumes:
      - .:/home/ticketing/app
    environment:
      - UWSGI_INI=/home/ticketing/app/docker/uwsgi_dev.ini
    ports:
      - "8080:80"
    depends_on:
      - db
      - redis
    networks:
      - ticketing_public
      - default
  migrator:
    build:
      context: .
      target: migrator
    env_file: .env
    volumes:
      - .:/home/ticketing/app
    depends_on:
      - db
      - redis
  worker:
    build:
      context: .
      target: worker
    env_file: .env
    volumes:
      - .:/home/ticketing/app
    depends_on:
      - db
      - redis
  beat:
    build:
      context: .
      target: beat
    env_file: .env
    volumes:
      - .:/home/ticketing/app
    depends_on:
      - db
      - redis
  flower:
    build:
      context: .
      target: flower
    env_file: .env
    volumes:
      - .:/home/ticketing/app
    ports:
      - "5555:5555"
    depends_on:
      - db
      - redis
```

Any help would be appreciated. Thanks
